version: 2.1

orbs: 
  oxygen: ttrahan/oxygen-orb@dev:first

workflows:
  install_and_start_server:
    jobs:
      - oxygen/install-start-server:
          selenium-minor-version: 3.5
          selenium-patch-version: 3.5.3
          install-dotnet-framework: false
